### ISSUE TITLE
CM-10: edit homepage

### ISSUE THREAD

**Issue by eguefif** [eguefif/career_manager#21]
# Context
At the moment, we want to be able to edit the home page.

# Task
- [x] Add the JS/HTML to edit the frontpage
- [x] Add the routing that will handle the post json
- [x] Make the controller to handle the homepage
- [ ] Model validation

**Comment by eguefif** [comment]
# Serde problem
I had a problem with serde json. The documentation does not seem to be up to date. Here is the solution:
```rust
use crate::connector::{SqlEngine, SqlType};
use serde::{Deserialize, Serialize};

pub const BASE_PICTURE_PATH: &str = "/images/";

#[derive(Serialize, Deserialize, Debug)]
pub struct Profile {
    pub display_name: String,
    pub description: String,
    pub picture: String,
    pub id: String,
}
```

```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] } # needed to use Deserialize and Serialize
serde_json = "1.0"
```
